#!/bin/sh
killall sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

~/.config/polybar/launch.sh

bspc monitor DP-0 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           8
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config center_pseudo_tiled true
